### ISSUE TITLE
Error: https://dietercasier.solidcommunity.net/profile/card#me is not a valid webId.

### ISSUE THREAD

**Issue by dieterc** [NoelDeMartin/umai#12]
After login with another solid pod I was able to create a cookbook but I was not able to save a recipe, also I kept on being disconnected. Any idea why?

Error details:
```
Error: https://dietercasier.solidcommunity.net/profile/card#me is not a valid webId.
    at https://umai.noeldemartin.com/assets/main.8f09a7a2.js:113:43062
    at f (https://umai.noeldemartin.com/assets/noeldemartin-utils.esm.8b1f171f.js:1:43188)
    at Generator._invoke (https://umai.noeldemartin.com/assets/noeldemartin-utils.esm.8b1f171f.js:1:42976)
    at Generator.next (https://umai.noeldemartin.com/assets/noeldemartin-utils.esm.8b1f171f.js:1:43617)
    at Gw (https://umai.noeldemartin.com/assets/noeldemartin-utils.esm.8b1f171f.js:1:62078)
    at a (https://umai.noeldemartin.com/assets/noeldemartin-utils.esm.8b1f171f.js:1:62284)
```

**Comment by NoelDeMartin** [comment]
Hi there,

I'm looking at that url `https://dietercasier.solidcommunity.net/profile/card#me` and I get this:

```ttl
@prefix : <#>.
@prefix acl: <http://www.w3.org/ns/auth/acl#>.

:me
    acl:trustedApp
            [
                acl:mode acl:Append, acl:Read, acl:Write;
                acl:origin <http://10.255.10.52:8080>
            ],
            [
                acl:mode acl:Append, acl:Read, acl:Write;
                acl:origin <https://umai.noeldemartin.com>
            ].
```

This doesn't seem to be a profile document, since it's missing the `foaf:PersonalProfileDocument` triple. Did you modify it manually? Or maybe a different app changed it?

You'll need to fix the profile and it should work. Also to note, besides the `foaf:PersonalProfileDocument` tripe it also seems to be missing a name, and saying `foaf:Person` on `:me`, etc.

**Comment by dieterc** [comment]
Normally I should have fixed the profile: https://dietercasier.solidcommunity.net/profile/card#me
When the application tries to create the cookbook I get another error:
`NetworkRequestError: Request failed trying to fetch https://dietercasier.solidcommunity.net/settings/privateTypeIndex.ttl
`
When I use a tool to see the contents of the pod I see the newly created container.

**Comment by NoelDeMartin** [comment]
Can you make sure that the `/settings/privateTypeIndex.ttl` document also exists? I have looked at your webId again and it's indeed listed in your profile, but since it's a private document I cannot look at it.

Also, whenever these things happen I always suggest to try with a different browser, or clear your browser's storage. It is possible that something is cached from the time it was not working and clearing the cache could fix it.

**Comment by dieterc** [comment]
I was using only Chrome and after your suggestion to use another browser everything works like a charm!
Thanks for helping me out so fast!

**Comment by NoelDeMartin** [comment]
You're welcome :) It should work in Chrome as well, you probably only need to clear the storage.
