### ISSUE TITLE
Direct link to recipe could offer user to login

### ISSUE THREAD

**Issue by josephguillaume** [NoelDeMartin/umai#18]
If I paste a link to a recipe directly in a browser where I am not logged in, I get 404: Not Found with a link to go home.

Instead of going home, logging in, and trying again, it would be useful to be offered to login directly on that page.

This assumes the link is indeed valid - if the user has actually pasted a link from someone else's pod instead of using the viewer, then this wouldn't work. Given that the url does not encode any information about the pod, logging in is probably the only way to tell anyway.

**Comment by NoelDeMartin** [comment]
Hey, thanks for opening an issue!

I think that's good idea, I'll look into it next time I do a release.

For the longer term, though, I'm still not convinced that this approach of having "pretty urls" is the best for Solid Apps. [As we discussed in the forum](https://forum.solidproject.org/t/should-solid-apps-have-pretty-urls/6308), one alterantive is having the recipe url encoded in the path, so for example instead of `/recipes/ramen` the path would be `/recipes/https%3A%2F%2Fpod.example.com%2Fcookbook%2Framen%23it`. That would remove this problem, and the need for a "viewer" altogether. But I'm still not convinced that having "ugly urls" is ultimately better :/.

So yeah, I don't know what I'll do in the end. But I'm still using pretty urls in [the work I'm currently doing](https://www.youtube.com/watch?v=awaaSorMYhk), so I guess this will continue being a problem.

**Comment by NoelDeMartin** [comment]
Thanks again for the suggestion, I've added it in the release [v0.1.7](https://github.com/NoelDeMartin/umai/blob/main/CHANGELOG.md#v017---2024-12-03).

This is what the "not found" page looks like at the moment:

![image](https://github.com/user-attachments/assets/37278224-285d-49c4-a2fb-8c65636b3663)

I have to confess I'm not super happy with that page 😅. Some day I hope to improve it, but for now that should work.
