### ISSUE TITLE
SoukaiError: Error creating container at https://little-ducky.solidcommunity.net/cookbook/, returned 500 status code

### ISSUE THREAD

**Issue by jeff-zucker** [NoelDeMartin/umai#2]
[Please, explain here what you were trying to do when this error appeared]

Connected to a new account on solidcommunity.net. Accepted the /cookbook/ suggestion to create a cookbook and pressed continue, got this:

Stack trace:
```
SoukaiError: Error creating container at https://little-ducky.solidcommunity.net/cookbook/, returned 500 status code
    at Proxy.value (https://umai.noeldemartin.com/assets/main.1bcb845b.js:99:9402)
    at Proxy.<anonymous> (https://umai.noeldemartin.com/assets/main.1bcb845b.js:99:2495)
    at tryCatch (https://umai.noeldemartin.com/assets/noeldemartin-utils.esm.f4aaecaa.js:4:823)
    at Generator.invoke [as _invoke] (https://umai.noeldemartin.com/assets/noeldemartin-utils.esm.f4aaecaa.js:4:3070)
    at Generator.next (https://umai.noeldemartin.com/assets/noeldemartin-utils.esm.f4aaecaa.js:4:1445)
    at asyncGeneratorStep (https://umai.noeldemartin.com/assets/noeldemartin-utils.esm.f4aaecaa.js:5:13881)
    at _next (https://umai.noeldemartin.com/assets/noeldemartin-utils.esm.f4aaecaa.js:5:14106)
```

**Comment by NoelDeMartin** [comment]
Hey, thanks for opening the issue!

Unfortunately just looking at this I'm not sure what went wrong :sweat_smile: It seems like the POD returned a 500 trying to create the container, but without seeing the response I don't know why. I'll try to update error reporting so that the response body is included in this type of errors.

Although a 500 error, as far as I understand, is an internal server error so it's probably a bug or some unhandled edge-case in the server. If it were an authentication problem or something wrong on the app's part, it should return 401 or something else.

**Comment by jeff-zucker** [comment]
Thanks.  I'll try again when I get time and try to give a more detailed account.  The 500 is very odd because it is a server error.  I was able to manually create a container on the account with SolidOS, so creating the container isn't the problem.

Not directly related but another issue to  consider - you are apparently using POST to create the container so if I already have a /cookbook/ container, it will silently create /cookbook.34347u8073/.  Might be better to say "that name is taken, got another?".  Also you tell the user you are going to create Cookbook (capital C) but you create cookbook (small C).

**Comment by NoelDeMartin** [comment]
> Not directly related but another issue to consider - you are apparently using POST to create the container so if I already have a /cookbook/ container, it will silently create /cookbook.34347u8073/. Might be better to say "that name is taken, got another?". Also you tell the user you are going to create Cookbook (capital C) but you create cookbook (small C).

If the container already exists, I should get an error in response because I'm passing the `'If-None-Match: *` header. My code is already aware of that, and it does create a `cookbook-{uuid}` as fall back. Maybe in this scenario I should ask the user instead of doing it automatically... This behaviour makes sense in other apps where I'm not asking users for a location, though I guess here it would make sense. But I'm worried that someone didn't check the advanced options and knows nothing about containers.

About the casing, yes it's always in lowercase but you should be able to see that on the preview. It's converting the name into a slug, so for example if you write "My Awesome Container", the actual url will use `my-awesome-container`:

![image](https://user-images.githubusercontent.com/1517677/185444432-e99c5605-65fa-4781-b7e0-2b7f5e225227.png)

**Comment by NoelDeMartin** [comment]
I've released a new beta version that I think should fix this problem, I think it was related with https://github.com/nodeSolidServer/node-solid-server/issues/1703

Let me know if it still isn't working, and we can reopen the issue.
