### ISSUE TITLE
Authenticated use of the viewer

### ISSUE THREAD

**Issue by angelo-v** [NoelDeMartin/umai#23]
Currently the [viewer](https://umai.noeldemartin.com/viewer) only seems to work with public recipes, since it does not allow me to sign in. I would like to view also recipes that are non-public.

**Comment by NoelDeMartin** [comment]
Initially, I wanted to avoid this because I didn't want to have any authentication logic in the viewer (with all the redirects, etc.). But I think it makes sense to do it.

I also have to rethink the whole idea of the viewer, and I may remove it altogether as I recently explained [in the forum](https://forum.solidproject.org/t/should-solid-apps-have-pretty-urls/6308/10). I'll keep issue in mind when I look into that.

**Comment by angelo-v** [comment]
I like the approach having full URLs in the main apps much better

**Comment by NoelDeMartin** [comment]
I have fixed this in [v0.1.7](https://github.com/NoelDeMartin/umai/blob/main/CHANGELOG.md#v017---2024-12-03), you should be able to view private recipes now.

However, keep in mind that this only works if you're logged in. And it doesn't tell you to log in if you haven't already... Ideally, it would allow you to log in on that page, but as I mentioned I intend to remove the viewer altogether at some point. In the meantime, that should be enough.
