### ISSUE TITLE
Print to PDF?

### ISSUE THREAD

**Issue by xpat** [NoelDeMartin/umai#5]
Congratulations @NoelDeMartin. Umai has reached 0.1.0. just recently and I'm already able to make good use of it.  I'm racking my brains in a panic trying to figure out how to print this to PDF.  I exported the json-ld and made use of python3-pygmatize to hightlight the json fields and then was able to output it to some htmo by following the directions [here](https://askubuntu.com/questions/596241/creating-highlighted-pdf-from-json). But in my rush to get this to the chef of our restaurant I thought I'd reach out on this Saturday (no doubt a day off for most) and see if anyone has a quick fix.  Also, I thought it would be a nice feature to have in general, so perhaps it's already in the pipeline.  

Another enhancement I'm hoping for is functionality that allows pictures for the recipes.  If I knew how to program this myself and if I weren't in a tizzy I'd offer this as my contribution. But for now I can only offer it as a suggestion.

**Comment by NoelDeMartin** [comment]
Hey, thanks for opening an issue, and I love that you're asking for this :D

The truth is that initially, I started implementing this, and when you opened the Share dialog, one of the options was "print". However, after passing the idea around to a couple of people it seemed like there wasn't much interest, so in the end I removed it.

But I'll certainly add it back :D. The good news is that the way I was implementing it was nothing fancy, I was just taking advantage of the HTML. So you should be able to do it yourself by using the built-in print functionality of your browser. I just tried it though, and the output isn't as nice because I didn't pay any attention to the print styles since I removed that feature :(. But I guess you can do that in the meantime.

As per adding more images, that's also something that crossed my mind, but I don't think I'll do it in the short term because it's not so easy to implement :(. Maybe if more people is interested I can take a look, but there are a couple of challenges in terms of UX and file management so it wouldn't be trivial.

**Comment by NoelDeMartin** [comment]
Hey, thanks again for opening the issue!

I'm glad to say that printing is now possible in the app :tada:. As I mentioned, it uses the browser's native functionality, so it's possible that it doesn't look exactly the same in all browsers. But I've done some tests and it works pretty well.

You can print your recipes by opening the Share modal, and selecting the "Print" option. I've also added it in the viewer, so if anyone wants to check it out you can open [one of my recipes](https://umai.noeldemartin.com/viewer?url=https://noeldemartin.solidcommunity.net/cookbook/matcha-scones%23it) and click the "Print" button.

Here's how an example recipe looks like: [ramen.pdf](https://github.com/NoelDeMartin/umai/files/10948399/ramen.pdf)

**Comment by xpat** [comment]
Looks good. It seems to the ingredients show up but not the instructions. I printed my own recipe to pdf. I'll look into figuring it out. 

I've been really busy with the restaurant and cafe re-opening so I'll give more feedback or get more involved a little later. I'm subscribed to get updates and I've shown your sites umai and media kraken to potential SOLID users. It helps illustrate the potential. Such a nice UI and good functionality. Thanks again.
